# Changes here will be overwritten by Copier
_commit: v0.1.2
_src_path: gh:igembitsgoa/igem-wiki-starter
author: Soumodeep Sarkar
email: soumodeep.sarkar1@learner.manipal.edu
iGEM_official_team_name: MIT_MAHE
iGEM_team_name: MIT_MAHE
year: 2020